- id: secure-dependencies
  name: Snyk Security Scan
  entry: ./secure_dependencies.sh
  language: script
  description: Multi-language dependency vulnerability scanning with Snyk via Docker
  pass_filenames: false

- id: owasp-dependency-check
  name: OWASP Dependency-Check
  entry: ./owasp_dependency_check.sh
  language: script
  description: Analyze Java dependencies using local OWASP Dependency-Check installation
  pass_filenames: false

- id: gitleaks-local
  name: GitLeaks Secrets Scanner
  entry: ./gitleaks.sh
  language: script
  description: Detect hardcoded secrets like passwords, api keys, and tokens in git repos
  pass_filenames: false

- id: semgrep-sast
  name: Semgrep SAST Scanner
  entry: ./semgrep.sh
  language: script
  description: Static analysis security testing with Semgrep
  pass_filenames: false

- id: vulnerability-summary
  name: Security Summary Report
  entry: ./vulnerability_summary.sh
  language: script
  description: Display executive security summary using custom script
  pass_filenames: false

- id: vulnerability-summary-ai
  name: Generate AI Vulnerability Summary
  entry: vulnerability_summary_ai
  language: python
  description: Generates a Markdown summary of security scan results using the Gemini API.
  pass_filenames: false
  additional_dependencies: [google-generativeai, python-dotenv]

- id: bandit-python-sast
  name: Bandit Python Security Scanner
  entry: ./bandit_python_sast.sh
  language: script
  description: Security linter for Python code
  pass_filenames: false

- id: syft-sbom-scan
  name: Syft SBOM Scanner
  entry: ./syft_scan.sh
  language: script
  description: Gera SBOM (Software Bill of Materials) e análise de dependências com Syft via Docker
  pass_filenames: false

- id: grype-vulnerability-scan
  name: Grype Vulnerability Scanner
  entry: ./grype_scan.sh
  language: script
  description: Detecta vulnerabilidades usando Grype via Docker (preferencialmente usando SBOM do Syft)
  pass_filenames: false
