[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "precommit-hook-custom"
version = "0.1.0"
description = "Custom pre-commit hooks"
dependencies = []
